# Generated by Django 5.0.7 on 2024-07-30 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=250, verbose_name="Место выполнения"),
                ),
                ("start_at", models.TimeField(verbose_name="Время начала выполнения")),
                ("action", models.CharField(max_length=250, verbose_name="Действие")),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Промежуток между выполнениями привычки в днях.",
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "is_pleasure",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                ("runtime", models.DurationField(verbose_name="Время на выполнение")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "execute_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата выполнения"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
